name: Build/Distribute blocbench

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.4
  
      - name: Install Electron Bundler
        run: yarn add electron-builder --dev

      - name: Build blockbench executable
        run: npm run windows
        
      - name: Minio Deploy
        uses: mamal72/minio-perfect-deploy-action@main
        with:
          endpoint: ${{ secrets.BLOCKBENCH_MINIO_PROD_URL }}
          access_key: ${{ secrets.BLOCKBENCH_MINIO_PROD_ACCESSKEY }}
          secret_key: ${{ secrets.BLOCKBENCH_MINIO_PROD_SECRETKEY }}
          bucket: 'blockbench'
          source_dir: 'dist'
          target_dir: '/'


