name: blockbench-distribute

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.4
  
      - name: Install Electron Bundler
        run: yarn add electron-builder --dev

      - name: Install Minio Client
        run: |
          go install github.com/minio/mc@latest

      - name: Build blockbench executable
        run: npm run windows
        
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'package.json'
            prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}  

      - name: Deploy To Minio
        run: |
          mc alias set deploy ${{ secrets.BLOCKBENCH_MINIO_PROD_URL }} ${{ secrets.BLOCKBENCH_MINIO_PROD_ACCESSKEY }} ${{ secrets.BLOCKBENCH_MINIO_PROD_SECRETKEY }}
          mc mv dist/Blockbench_${{steps.version.outputs.prop}}.exe "deploy/blockbench/${{steps.version.outputs.prop}}/Blockbench_${{steps.version.outputs.prop}}.exe"


