name: Build/Distribute blocbench

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.4

      - name: Build electron app
        run: npm run dist
