name: Build/Distribute blocbench

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.4
  
      - name: Install Electron Bundler
        run: yarn add electron-builder --dev

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt-get install --install-recommends wine-stable
          sudo apt install --install-recommends winehq-stable

      - name: Build blockbench executable
        run: npm run windows
        
      - name: Minio upload
        uses: lovellfelix/minio-deploy-action@v1.1.1
        with:
          # Minio endpoint of object storage host
          endpoint: ${{ secrets.BLOCKBENCH_MINIO_PROD_URL }}
          # Minio access key (username)
          access_key: ${{ secrets.BLOCKBENCH_MINIO_PROD_ACCESSKEY }}
          # Minio secret key (password)
          secret_key: ${{ secrets.BLOCKBENCH_MINIO_PROD_SECRETKEY }}
          # Set the target minio bucket for deployment.
          bucket: 'blockbench'
          # Set an input directory for deployment.
          source_dir: 'dist'
          # Set a target directory for deployment (with a leading slash).
          target_dir: '/'


