name: Build Electron App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Clean up dist and node_modules if they exist
        run: |
          if (Test-Path -Path dist) { Remove-Item -Recurse -Force dist }
          if (Test-Path -Path node_modules) { Remove-Item -Recurse -Force node_modules }
        shell: pwsh

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for Windows
        run: |
          CSC_IDENTITY_AUTO_DISCOVERY=false CSC_LINK=npx electron-builder -- --win --x64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-windows
          path: dist/

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Clean up dist and node_modules
        run: rm -rf dist node_modules

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for macOS ARM64
        run: |
          CSC_IDENTITY_AUTO_DISCOVERY=false CSC_LINK=npx electron-builder -- --mac --arm64

      - name: Locally sign the file
        run: codesign --deep --force --verbose --sign ./dist/mac-arm64/Blockbench.app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-macos
          path: dist/
