name: Build Electron App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for Windows
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install electron-builder
          npx electron-builder --config ./electron.yml --win --x64
        shell: pwsh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-windows
          path: dist/

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for macOS ARM64
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install electron-builder
          npx electron-builder --config ./electron.yml --mac --arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-macos
          path: dist/
