name: Sync Blockbench Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/JannisX11/blockbench.git"
  # Workflow Token
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  # Optional, defaults to main
  UPSTREAM_BRANCH: "master"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "dev"
  # Optional merge arguments
  MERGE_ARGS: "-Xours"
  # Optional push arguments
  PUSH_ARGS: ""

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

# Jobs
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Sync and merge upstream repository with your current repository
        # uses: dabreadman/sync-upstream-repo@f61088b9adb9220c5d518a405cd1ab52c0500e4d
        uses: dabreadman/sync-upstream-repo@v1.2.0.b
        with:
          # URL of gitHub public upstream repo
          upstream_repo: ${{ env.UPSTREAM_URL }}
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          # Branch to merge into downstream
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          # GitHub Bot token
          token: ${{ env.WORKFLOW_TOKEN }}
          # Git merge arguments
          merge_args: ${{ env.MERGE_ARGS }}
          # Git push arguments
          # push_args: # optional, default is 
